### PR TITLE
Rainbow parentheses

### PR DESCRIPTION
**Pull request by honzabrecka**
Hi, at first thank you for this project!

I'm using it to teach clojure/clojurescript to my colleagues, but they always complain, that it would be much more easier to read examples if there were rainbow parentheses. So, here is my quick fix. And I can confirm that they have better progress now.

### CODE REVIEW

**Comment by mkremins** [comment]
Thanks for the pull request!

It looks like this patch causes an error when I try to load the first koan in the "functions" category, because some part of the code is attempting to construct an HTML element with the tag name `(` (an open parentheses character). I'm not quite sure why that's happening – maybe there's a vector with the string `"("` as its first element that's getting interpreted/rendered as Hiccup somehow?

Not merging this for now, but would like to if you can figure out what's going wrong and fix it.

**Comment by honzabrecka** [comment]
Fixed.

**Comment by mkremins** [comment]
New issue: because of the way code strings are reassembled before evaluation, koans that rely on the `#()` shorthand syntax for anonymous functions (such as the fourth and fifth koans in the "functions" category) are unsolvable. A space is inserted between the `#` and `(` characters during reassembly, and the reader doesn't know how to parse that.

**Comment by honzabrecka** [comment]
Thanks for your review! I tried just few koans and I had a wrong presumption that it will work for the rest of them. Now, everything should work as expected. I also slightly improved the code-box by adding underline to each input element.

**Comment by mkremins** [comment]
LGTM 👍

**Pull request merged**
